services:
  # https://hub.docker.com/r/opensearchproject/opensearch
  opensearch:
    build: .
    #image: opensearchproject/opensearch:2.19.3
    environment:
      #- bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- xpack.security.enabled=false
      # `no new native processes can be started` エラー回避
      # https://stackoverflow.com/questions/60182669/elastic-search-error-native-controller-process-has-stopped-no-new-native-pro
      - discovery.type=single-node
      # https://hub.docker.com/r/opensearchproject/opensearch#how-to-use-this-image
      # > Note: For OpenSearch 2.12 and later, a custom password for the admin user is required to be passed to set-up and utilize demo configuration.
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Super-secret1
      #
      - plugins.security.disabled=true
    entrypoint: bash -c " /usr/share/opensearch/tmp/entrypoint.sh "
    volumes:
      - ./entrypoint.sh:/usr/share/opensearch/tmp/entrypoint.sh

    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
