services:
  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"  # Tempo Query (HTTP)
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./data:/tmp/tempo
