[project]
name = "elasticsearch-ltr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch>=8.17.2",
    "faker>=37.1.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "xgboost>=3.0.0",
]
