services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-sandbox
    ports:
      - "5432:5432"
    environment:
      LANG: ja_JP.utf8
      POSTGRES_USER: sandbox_user
      POSTGRES_DB: sandbox_db
      POSTGRES_PASSWORD: sandbox_pw
    command: -c max_connections=14
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./init_db/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresql-data:
    driver: local
