version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    # build: .
    container_name: postgre-sandbox
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sandbox_user
      POSTGRES_DB: sandbox_db
      POSTGRES_PASSWORD: sandbox_pw
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:
    driver: local
