version: 0.2

phases:
  pre_build:
    commands:
      - echo pre_build
      - .aws/download-swagger-ui.sh
  build:
    commands:
      - npm install
      - mkdir -p dist
      - mv swagger-ui dist/swagger-ui
      - echo testtest > dist/test.txt
      - echo foo > dist/foo.txt
  post_build:
    commands:
      - echo post_build
      #- tar czvf dist/my-app.tar.gz my-app
artifacts:
  files:
    - '**/*'
  base-directory: dist
