version: 0.2

phases:
  pre_build:
    commands:
      - echo pre_build
      - .aws/download-swagger-ui.sh
  build:
    commands:
      - npm install
      - mkdir -p build
      - mv swagger-ui build/swagger-ui
      - echo testtest > build/test.txt
      - echo foofoo > build/foo.txt
      - echo bar > build/bar.txt
      - echo baz > build/baz.txt
      # テスト
      - ls -l *ers
  post_build:
    commands:
      - echo post_build
      #- tar czvf build/my-app.tar.gz my-app
artifacts:
  files:
    - '**/*'
  base-directory: build
