import React from 'react';
import ReactDOM from 'react-dom';

import './main';
import {ArwesThemeProvider, Button, FrameBox, StylesBaseline, Text} from "@arwes/core";
import {Animator, AnimatorGeneralProvider} from "@arwes/animation";
import {bootstrap, openFilePicker, Tracing} from "./main";

export const FONT_FAMILY_ROOT = '"Titillium Web", sans-serif';
export const FONT_FAMILY_CODE = '"Source Code Pro", monospace';

const generalAnimator = { duration: { enter: 500, exit: 500 } };

class App extends React.Component {
    state = {
        welcome: true,
        tracing: false,
    }

    async handleClick(closeWelcomeContent) {
        const fileHandle = await openFilePicker();
        closeWelcomeContent();
        await new Promise(resolve => setTimeout(resolve, generalAnimator.duration.exit + 200));
        this.setState({
            welcome: false,
            tracing: true,
        });
        await bootstrap(fileHandle);
    }

    render() {
        return (
            <div>
                <Welcome welcome={this.state.welcome} handleClick={(action) => this.handleClick(action)}/>
                <Tracing tracing={this.state.tracing}/>
            </div>
        );
    }
}

const Welcome = (props) => {
    const [activate, setActivate] = React.useState(true);

    if (!props.welcome) {
        return null;
    }

    return (
        <div style={{marginTop: "50px"}}>
            <ArwesThemeProvider>
                <StylesBaseline styles={{
                    'html, body': { fontFamily: FONT_FAMILY_ROOT },
                    'code, pre': { fontFamily: FONT_FAMILY_CODE },
                    'body': { textAlign: "center" }
                }} />
                <AnimatorGeneralProvider animator={generalAnimator}>
                    <Animator animator={{ activate, manager: 'stagger' }}>
                        <Text as='h1'>Tracing tool for discv5</Text>
                        <hr />
                        <FrameBox>
                            <div style={{width: 700, height: 300}}>
                                <div style={{textAlign: "left"}}>
                                    <Text as='p'>3D tracing tool for <a href="https://github.com/ethereum/devp2p/blob/master/discv5/discv5.md">Node Discovery Protocol v5</a>, which visualize communications between nodes and the state of DHT.</Text>
                                    <Text as='p'>This tool parses tracing logs generated by discv5 library. Currently, the tracing log feature for discv5 library is under develop on my experimental branch <a href="https://github.com/ackintosh/discv5/tree/experimental-feature/tracing">ackintosh/discv5</a> forked from sigp/discv5 :) .</Text>
                                    <Text as='p'>Here is a <a href="#">sample tracing log</a> generated by the experimental implementation, please try with this!</Text>
                                </div>
                                <div>
                                    <Button
                                        animator={{ activate }}
                                        onClick={() => {props.handleClick(() => setActivate(!activate));}}
                                    >
                                        <Text>Choose Tracing Log File</Text>
                                    </Button>
                                </div>
                            </div>
                        </FrameBox>
                    </Animator>
                </AnimatorGeneralProvider>
            </ArwesThemeProvider>
        </div>
    );
};

ReactDOM.render(
    <React.StrictMode>
        <App />
    </React.StrictMode>,
    document.getElementById('root')
);

