[package]
name = "crate-arti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arti-client = "0.6.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
