version: '3.7'
services:
  mongo:
    image: mongo:4.4.3
    container_name: mongo-sandbox
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sandbox_user
      MONGO_INITDB_ROOT_PASSWORD: sandbox_pw
      MONGO_INITDB_DATABASE: sandbox_db
      TZ: Asia/Tokyo
