# Official example
# https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml

lint:
  files:
    exclude:
      # 公式からダウンロードしたファイルを除外
      - protocol-buffers/kotlin/src/main/proto/code.proto
      - protocol-buffers/kotlin/src/main/proto/error_details.proto
  rules_option:
    max_line_length:
      max_chars: 120
