# Official example
# https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml

lint:
  files:
    exclude:
      # 公式からダウンロードしたファイルを除外
      - protocol-buffers/kotlin/src/main/proto/code.proto
      - protocol-buffers/kotlin/src/main/proto/error_details.proto
  # https://github.com/yoheimuta/protolint#rules
  rules:
    remove:
      - ORDER
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
  rules_option:
    max_line_length:
      max_chars: 120
