# 配下のパッケージでCargo.tomlを分けたい & IntelliJのプロジェクトは分けたくないので、
# 各パッケージをワークスペースにまとめる
# <Cargoのワークスペース>
# https://doc.rust-jp.rs/book/second-edition/ch14-03-cargo-workspaces.html
# * `Cargo.lock` は親ディレクトリ(rust)に集約される（各パッケージで共有する）
# * `target` ディレクトリ(出力ディレクトリ)も親ディレクトリに集約される
[workspace]
members = [
  "arithmetic",
  "async-await",
  "dns",
  "crate-chrono",
  "crate-env_logger",
  "crate-lazy_static",
  "crate-reqwest",
  "crate-uint",
  "tokiors",
  "iterator",
  "level-db",
  "macros",
  "primitives-stdlibs",
  "procon",
  "references-borrowing",
  "result",
  "socket-programming",
  "threading",
  "tower-of-hanoi"
]

