service: appsync-sample-with-serverless
provider:
  name: aws
  stage: test
  region: ap-northeast-1

plugins:
  - serverless-dynamodb-local
  - serverless-appsync-plugin
  - serverless-appsync-offline
  - serverless-offline

# プラグイン関連の設定
custom:
  # AppSync Offline Plugin
  # https://github.com/aheissenberger/serverless-appsync-offline
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        endpoint: "http://localhost:8000"
        region: localhost
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    stages:
      - test
    seed:
      test:
        sources:
          - table: Users
            sources: [seed-data/generated/Users.json]

  # Serverless-AppSync-Plugin
  # https://github.com/sid88in/serverless-appsync-plugin#configuring-the-plugin
  appSync:
    # エンドポイントの名
    name: appsync-serverless-sample
    # AppSyncの認証方法
    authenticationType: API_KEY
    schema: schema.graphql
    # マッピングテンプレートのVTLファイルの格納先
    # デフォルトはmapping-templates
    mappingTemplatesLocation: mapping-templates
    # リゾルバー定義
    mappingTemplates:
      - type: Query
        # リゾルバーを紐づけるスキーマのフィールド名
        field: user
        kind: UNIT # UNIT|PIPELINE (デフォルトはUNIT)
        dataSource: dynamo_db_users
        # リクエストマッピングテンプレートのパス
        # ファイルパスはmappingTemplatesLocationで指定したパスからの相対パス
        request: 'GetUser.req.vtl'
        # レスポンスマッピングテンプレートのパス
        response: 'GetUser.res.vtl'
    # データソースを指定(複数指定可能)
    dataSources:
      - type: AMAZON_DYNAMODB
        name: dynamo_db_users
        description: 'ユーザー情報テーブル'
        config:
          tableName: Users

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: 'Users'
