[package]
name = "crate-testground-sdk-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
testground = "0.1.1"
async-std = { version = "1.10", features = [ "attributes" ] }
rand = "0.8.5"
