# https://github.com/styfle/cancel-workflow-action#advanced

# workflow_idは下記で確認
# https://api.github.com/repos/ackintosh/sandbox/actions/workflows

name: cancel previous runs
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # https://github.com/styfle/cancel-workflow-action/releases
      - uses: styfle/cancel-workflow-action@514c783 # 0.7.0
        with:
          workflow_id: 2791194,4114599,4991388,1168326
          access_token: ${{ github.token }}
