name: Linkcheck

on:
  push:

jobs:
  linkcheck:
    name: Check broken links
    runs-on: ubuntu-latest
    services:
      mdbook-service: # サービス名
        image: peaceiris/mdbook:latest
        ports:
          - 3000:3000
        options: --entrypoint '["/usr/bin/mdbook", "serve"]'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

