name: Linkcheck

on:
  push:

jobs:
  linkcheck:
    name: Check broken links
    runs-on: ubuntu-latest
      #services:
      #  mdbook-service: # サービス名
      #    image: peaceiris/mdbook:latest
      #    ports:
      #      - 3000:3000
      #    options: --entrypoint "mdbook serve"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Serves a book
        run: docker run -v ${{ github.workspace }}/mdbook:/book -p 3000:3000 -d peaceiris/mdbook:latest serve
      - name: Run linkcheck
        uses: filiph/linkcheck@v2.0.15+1
        with:
          arguments: localhost:3000

