name: Linkcheck

on:
  push:

jobs:
  linkcheck:
    name: Check broken links
    runs-on: ubuntu-latest
      #services:
      #  mdbook-service: # サービス名
      #    image: peaceiris/mdbook:latest
      #    ports:
      #      - 3000:3000
      #    options: --entrypoint "mdbook serve"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Serves a book
        run: docker run -v ${{ github.workspace }}/mdbook:/book --name book -p 3000:3000 -d peaceiris/mdbook:latest serve --hostname 0.0.0.0
      - name: tes
        run: docker logs book
      - name: Run linkcheck
        uses: filiph/linkcheck@v2.0.15+1
        with:
          arguments: 127.0.0.1:3000

