name: Run PHPUnit

on: [push, pull_request]

# 指定したバージョンのPHPや拡張をセットアップするGitHub Action
# https://github.com/shivammathur/setup-php

# 参考
# * PHPUnit
# https://github.com/sebastianbergmann/phpunit/blob/master/.github/workflows/ci.yml
# * Predis
# https://github.com/predis/predis/blob/main/.github/workflows/tests.yml

jobs:
  phpunit:
    name: Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
    defaults:
      run:
        working-directory: php/phpunit
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          # extensions: xdebug
        env:
          fail-fast: true

      - name: Install dependencies with composer
        run: composer install

      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit
