name: Run PHPUnit

on: push

# 指定したバージョンのPHPや拡張をセットアップするGitHub Action
# https://github.com/shivammathur/setup-php

# 参考
# * PHPUnit
# https://github.com/sebastianbergmann/phpunit/blob/master/.github/workflows/ci.yml

jobs:
  phpunit:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer, phpunit
          # extensions: xdebug
        env:
          fail-fast: true

      - name: Install dependencies with composer
        working-directory: ./php/phpunit
        run: ls -l && ls -l ../..

      - name: Run tests with phpunit
        working-directory: ./php/phpunit
        run: phpunit
