# https://docs.github.com/ja/actions/guides/publishing-docker-images#
# *** 2021-02時点では、上記ページのサンプルは docker/build-push-action の v1 を使っているので古い ***

# v1からv2への移行ガイド
# https://github.com/docker/build-push-action/blob/master/UPGRADE.md#simple-workflow
# Tags with ref and Git labels
# https://github.com/docker/build-push-action/blob/master/UPGRADE.md#tags-with-ref-and-git-labels

name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=ackintosh/sandbox
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            exit 1
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/marketplace/actions/docker-login#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: sqldef/Dockerfile.alpine
          push: true
          tags: ${{ steps.prepare.outputs.tags }}
