# https://docs.github.com/ja/actions/guides/publishing-docker-images#

# v1からv2への移行ガイド
# https://github.com/docker/build-push-action/blob/master/UPGRADE.md#simple-workflow
# Tags with ref and Git labels
# https://github.com/docker/build-push-action/blob/master/UPGRADE.md#tags-with-ref-and-git-labels

name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=ackintosh/sandbox
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            exit 1
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: sqldef/Dockerfile.alpine
          push: true
          tags: ${{ steps.prep.outputs.tags }}
