name: Rust IPv6

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: test ipv6
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Protocol Buffer Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Run IPv6 test
      working-directory: rust/crate-if-addrs
      run: cargo test -- --show-output

